# NumPy

In [1]:
# Introduction to NumPy
import numpy as np

In [2]:
list1 = [0,1,2,3,4]

In [3]:
print(list1)

[0, 1, 2, 3, 4]


In [4]:
arr1d = np.array(list1)

In [5]:
arr1d

array([0, 1, 2, 3, 4])

In [6]:
list1.append(5)

In [7]:
# Size cannot be changed for NumPy array
# NumPy array is used for manipualtion

In [8]:
list1+2

TypeError: can only concatenate list (not "int") to list

In [9]:
arr1d + 2

array([2, 3, 4, 5, 6])

In [10]:
list2 = [[1,1,1],[2,2,2],[3,3,3]]
print(list2)

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]


In [11]:
arr2d = np.array(list2)

In [12]:
print(arr2d)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [13]:
type(arr2d)

numpy.ndarray

In [14]:
arr2d.dtype

dtype('int32')

In [15]:
arr2d = np.array(list2, dtype='float' )
type(arr2d)

numpy.ndarray

In [16]:
arr2d.dtype

dtype('float64')

In [17]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [18]:
arr2d = arr2d.astype('int')

In [19]:
arr2d.dtype

dtype('int32')

In [20]:
arr2d.astype('str')

array([['1', '1', '1'],
       ['2', '2', '2'],
       ['3', '3', '3']], dtype='<U11')

In [21]:
list1

[0, 1, 2, 3, 4, 5]

In [22]:
list1.append('6')

In [23]:
list1

[0, 1, 2, 3, 4, 5, '6']

In [24]:
# list can be collection of heterogenous elements
# Np array is collection of homogenous elements

In [25]:
# conversion of np array to list
np2list = arr2d.tolist()

In [26]:
print(np2list)

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]


In [27]:
arr2d.tostring() # ASCII string

b'\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00'

In [28]:
arr2d.tobytes()

b'\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00'

In [29]:
# Numpy dtype and shape

In [30]:
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [31]:
arr2d = arr2d.astype('float')

In [32]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [33]:
print("Shape: ", arr2d.shape)

Shape:  (3, 3)


In [34]:
arr2d.dtype

dtype('float64')

In [35]:
arr2d.size

9

In [36]:
arr1d.size

5

In [37]:
arr2d.ndim

2

In [38]:
arr1d.ndim

1

In [39]:
arr1d

array([0, 1, 2, 3, 4])

In [40]:
arr1d = arr1d * arr1d # element by element operation

In [41]:
arr1d

array([ 0,  1,  4,  9, 16])

In [42]:
arr1d[0]

0

In [43]:
arr1d[2]

4

In [44]:
len(arr1d)

5

In [45]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [46]:
arr2d[0]

array([1., 1., 1.])

In [47]:
arr2d[0][0]

1.0

In [48]:
arr2d[1][0]

2.0

In [49]:
boolarr = arr2d < 3

In [50]:
boolarr

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [51]:
arr2d[boolarr]

array([1., 1., 1., 2., 2., 2.])

In [52]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [53]:
arr2d[::-1,]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [54]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]

In [55]:
arr2d = np.array(list2)

In [56]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr2d[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

# np.nan , np.inf

In [58]:
np.nan

nan

In [59]:
np.inf

inf

In [60]:
# Operation cannot be performed on this number

In [61]:
arr2d
arr2d = arr2d.astype('float')

In [62]:
arr2d[0][0] = np.nan # works only for float data type

In [63]:
arr2d

array([[nan,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [64]:
arr2d[0][1] = np.inf

In [65]:
arr2d

array([[nan, inf,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [66]:
np.isnan(arr2d)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [67]:
np.isinf(arr2d)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [68]:
missing_flag = np.isnan(arr2d) | np.isinf(arr2d)

In [69]:
missing_flag

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [70]:
# replacing inf and nan with zero

In [71]:
arr2d[missing_flag] = 0

In [72]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

# Statistical Operation

In [73]:
# mean, std, var

In [74]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [75]:
arr2d.mean()

4.666666666666667

In [76]:
arr2d.max()

9.0

In [77]:
arr2d.min()

0.0

In [78]:
arr2d.std()

3.0550504633038935

In [79]:
arr2d.var()

9.333333333333334

In [80]:
print(arr2d)
arr2d.squeeze()

[[0. 0. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [81]:
arr2d.diagonal()

array([0., 5., 9.])

In [82]:
arr2d.cumsum()

array([ 0.,  0.,  3.,  7., 12., 18., 25., 33., 42.])

In [83]:
# Slicing of np array

In [84]:
arr = arr2d[:2,:2]

In [85]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [86]:
arr

array([[0., 0.],
       [4., 5.]])

In [87]:
print(arr2d[1:3,1:3])

[[5. 6.]
 [8. 9.]]


In [88]:
print(arr2d[1:3,1:2])

[[5.]
 [8.]]


In [89]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [90]:
arr2d.reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [91]:
arr2d.reshape(1,9)

array([[0., 0., 3., 4., 5., 6., 7., 8., 9.]])

In [92]:
arr2d.reshape(9,1)

array([[0.],
       [0.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.],
       [9.]])

In [93]:
arr2d.ndim

2

In [94]:
arr2d.flatten()
print(arr2d)

[[0. 0. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [95]:
arr2d.ndim

2

In [96]:
arr2d.ravel()
print(arr2d)

[[0. 0. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Sequence, repetitions and random number

In [97]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [98]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [99]:
np.linspace(1,50,9)

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

In [100]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [101]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [102]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [103]:
a = [1,2,3]

In [104]:
a

[1, 2, 3]

In [105]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [106]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [107]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [108]:
np.repeat(arr2d,3)

array([0., 0., 0., 0., 0., 0., 3., 3., 3., 4., 4., 4., 5., 5., 5., 6., 6.,
       6., 7., 7., 7., 8., 8., 8., 9., 9., 9.])

In [109]:
np.random.rand(3,3)

array([[0.73582065, 0.17260927, 0.15251267],
       [0.88698845, 0.70758274, 0.41588346],
       [0.85264121, 0.67806189, 0.70402739]])

In [110]:
np.random.rand(3,3)

array([[0.80763416, 0.31767583, 0.11974059],
       [0.73046913, 0.86437449, 0.20599967],
       [0.63322063, 0.6144089 , 0.2179    ]])

In [111]:
np.random.randint(1,10,[3,3])

array([[2, 4, 5],
       [4, 8, 1],
       [9, 8, 2]])

In [112]:
np.random.seed(1)

In [113]:
np.random.randint(0,10,[3,3])

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [115]:
np.arange(1,5)

array([1, 2, 3, 4])

In [116]:
np.arange(1,5, dtype = 'float')

array([1., 2., 3., 4.])

In [117]:
np.arange(1,5, dtype = 'str')

ValueError: no fill-function for data-type.

In [118]:
np.arange(1,10,3)

array([1, 4, 7])

In [119]:
np.arange(1,10,4, dtype = 'float')

array([1., 5., 9.])

In [120]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [121]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [122]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [123]:
np.logspace(1,100)

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

In [124]:
np.logspace(1,100,5)

array([1.00000000e+001, 5.62341325e+025, 3.16227766e+050, 1.77827941e+075,
       1.00000000e+100])

In [126]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [127]:
np.ones([1,1])

array([[1.]])

In [128]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [129]:
a = [1,2,3]

In [130]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [131]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [132]:
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [133]:
np.repeat(arr2d,3)

array([0., 0., 0., 0., 0., 0., 3., 3., 3., 4., 4., 4., 5., 5., 5., 6., 6.,
       6., 7., 7., 7., 8., 8., 8., 9., 9., 9.])

In [135]:
np.random.rand(3,3)

array([[0.93553907, 0.84631092, 0.31327352],
       [0.52454816, 0.44345289, 0.22957721],
       [0.53441391, 0.91396202, 0.45720481]])

In [136]:
np.random.randn(3,3)

array([[ 0.67723401, -0.10687843,  0.72527406],
       [ 0.93488915,  1.11829698,  0.05561319],
       [ 0.37665664,  0.37613502, -0.16419077]])

In [137]:
np.random.randint(1,10,[3,3])

array([[9, 8, 4],
       [7, 6, 2],
       [4, 5, 9]])

In [138]:
np.random.randint(1,10,[3,3])

array([[2, 5, 1],
       [4, 3, 1],
       [5, 3, 8]])

In [140]:
np.random.randint(0,10)

7

In [141]:
np.random.seed(1)
arr2d

array([[0., 0., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [143]:
np.unique(arr2d)

array([0., 3., 4., 5., 6., 7., 8., 9.])

In [149]:
np.random.seed(0)
np.random.rand(3,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [151]:
np.random.rand(3,3)

array([[0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329]])

In [152]:
uniques, counts = np.unique(arr2d, return_counts= True)

In [153]:
uniques

array([0., 3., 4., 5., 6., 7., 8., 9.])

In [154]:
counts

array([2, 1, 1, 1, 1, 1, 1, 1], dtype=int64)