# More about NumPy

In [3]:
import numpy as np
arr = np.array([8,94,8,56,1,3,4,5,7])
print(arr)

[ 8 94  8 56  1  3  4  5  7]


In [4]:
index_gt10 = np.where(arr>10)

In [5]:
index_gt10

(array([1, 3], dtype=int64),)

In [8]:
arr[index_gt10]

array([94, 56])

In [9]:
arr[arr>10]

array([94, 56])

In [10]:
arr>10

array([False,  True, False,  True, False, False, False, False, False])

In [11]:
np.where(arr>10, 'gt10', 'lt10')

array(['lt10', 'gt10', 'lt10', 'gt10', 'lt10', 'lt10', 'lt10', 'lt10',
       'lt10'], dtype='<U4')

In [12]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [13]:
arr.max()

94

In [14]:
arr.argmax()

1

In [16]:
arr[arr.argmin()]

1

In [17]:
arr.argmin()

4

In [18]:
arr.min()

1

# read and write csv file

In [19]:
#np.genfromtxt(), np.loadtxt()

In [29]:
data = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',delimiter=',', 
                     skip_header = 1, filling_values= -1000, dtype = 'float')

In [30]:
print(data)

[[   18.     8.   307. ...    70.     1. -1000.]
 [   15.     8.   350. ...    70.     1. -1000.]
 [   18.     8.   318. ...    70.     1. -1000.]
 ...
 [   32.     4.   135. ...    82.     1. -1000.]
 [   28.     4.   120. ...    82.     1. -1000.]
 [   31.     4.   119. ...    82.     1. -1000.]]


In [31]:
data.shape

(392, 9)

In [32]:
data

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [33]:
data[:3]

array([[ 1.800e+01,  8.000e+00,  3.070e+02,  1.300e+02,  3.504e+03,
         1.200e+01,  7.000e+01,  1.000e+00, -1.000e+03],
       [ 1.500e+01,  8.000e+00,  3.500e+02,  1.650e+02,  3.693e+03,
         1.150e+01,  7.000e+01,  1.000e+00, -1.000e+03],
       [ 1.800e+01,  8.000e+00,  3.180e+02,  1.500e+02,  3.436e+03,
         1.100e+01,  7.000e+01,  1.000e+00, -1.000e+03]])

In [35]:
np.set_printoptions(suppress= True)
data[:3]

array([[   18. ,     8. ,   307. ,   130. ,  3504. ,    12. ,    70. ,
            1. , -1000. ],
       [   15. ,     8. ,   350. ,   165. ,  3693. ,    11.5,    70. ,
            1. , -1000. ],
       [   18. ,     8. ,   318. ,   150. ,  3436. ,    11. ,    70. ,
            1. , -1000. ]])

In [43]:
data2 = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv',delimiter=',', 
                     skip_header = 1, dtype = object)

In [44]:
data2[:3]

array([[b'18', b'8', b'307', b'130', b'3504', b'12', b'70', b'1',
        b'"chevrolet chevelle malibu"'],
       [b'15', b'8', b'350', b'165', b'3693', b'11.5', b'70', b'1',
        b'"buick skylark 320"'],
       [b'18', b'8', b'318', b'150', b'3436', b'11', b'70', b'1',
        b'"plymouth satellite"']], dtype=object)

In [49]:
np.savetxt('data.csv',data, delimiter=',')

In [50]:
np.save('data.npy', data)

In [51]:
np.savez('data2.npz', data, data2)

In [52]:
d = np.load('data.npy')

In [53]:
d

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [54]:
d2 = np.load('data2.npz')

In [55]:
d2.files

['arr_0', 'arr_1']

In [56]:
d2['arr_1']

array([[b'18', b'8', b'307', ..., b'70', b'1',
        b'"chevrolet chevelle malibu"'],
       [b'15', b'8', b'350', ..., b'70', b'1', b'"buick skylark 320"'],
       [b'18', b'8', b'318', ..., b'70', b'1', b'"plymouth satellite"'],
       ...,
       [b'32', b'4', b'135', ..., b'82', b'1', b'"dodge rampage"'],
       [b'28', b'4', b'120', ..., b'82', b'1', b'"ford ranger"'],
       [b'31', b'4', b'119', ..., b'82', b'1', b'"chevy s-10"']],
      dtype=object)

# concat with row and col wise

In [58]:
arr1 = np.zeros([4,4])

In [59]:
arr2 = np.ones([4,4])

In [60]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
#np.concatenate, np.vstack, np.r_

In [63]:
np.concatenate([arr1, arr2], axis = 0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
np.vstack([arr1, arr2])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
np.r_[arr1, arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
np.concatenate([arr1, arr2], axis = 1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [67]:
np.hstack([arr1, arr2])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [68]:
np.c_[arr1, arr2]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

# sort a numpy array

In [71]:
arr = np.random.randint(1,10, [10,5])

In [72]:
arr

array([[6, 5, 9, 9, 5],
       [3, 9, 5, 9, 9],
       [1, 8, 9, 7, 7],
       [7, 1, 7, 1, 6],
       [4, 6, 2, 4, 6],
       [1, 4, 3, 2, 4],
       [1, 8, 5, 7, 5],
       [8, 5, 1, 3, 4],
       [8, 1, 8, 1, 3],
       [1, 8, 2, 6, 9]])

In [73]:
np.sort(arr, axis = 0)

array([[1, 1, 1, 1, 3],
       [1, 1, 2, 1, 4],
       [1, 4, 2, 2, 4],
       [1, 5, 3, 3, 5],
       [3, 5, 5, 4, 5],
       [4, 6, 5, 6, 6],
       [6, 8, 7, 7, 6],
       [7, 8, 8, 7, 7],
       [8, 8, 9, 9, 9],
       [8, 9, 9, 9, 9]])

In [74]:
np.sort(arr, axis = 1)

array([[5, 5, 6, 9, 9],
       [3, 5, 9, 9, 9],
       [1, 7, 7, 8, 9],
       [1, 1, 6, 7, 7],
       [2, 4, 4, 6, 6],
       [1, 2, 3, 4, 4],
       [1, 5, 5, 7, 8],
       [1, 3, 4, 5, 8],
       [1, 1, 3, 8, 8],
       [1, 2, 6, 8, 9]])

In [79]:
sorted_index = arr[:, 0].argsort()

In [80]:
arr[sorted_index]

array([[1, 8, 9, 7, 7],
       [1, 4, 3, 2, 4],
       [1, 8, 5, 7, 5],
       [1, 8, 2, 6, 9],
       [3, 9, 5, 9, 9],
       [4, 6, 2, 4, 6],
       [6, 5, 9, 9, 5],
       [7, 1, 7, 1, 6],
       [8, 5, 1, 3, 4],
       [8, 1, 8, 1, 3]])

In [81]:
arr

array([[6, 5, 9, 9, 5],
       [3, 9, 5, 9, 9],
       [1, 8, 9, 7, 7],
       [7, 1, 7, 1, 6],
       [4, 6, 2, 4, 6],
       [1, 4, 3, 2, 4],
       [1, 8, 5, 7, 5],
       [8, 5, 1, 3, 4],
       [8, 1, 8, 1, 3],
       [1, 8, 2, 6, 9]])

# working with dates

In [82]:
d = np.datetime64('2019-06-02 23:10:00')

In [83]:
d

numpy.datetime64('2019-06-02T23:10:00')

In [84]:
d + 1000

numpy.datetime64('2019-06-02T23:26:40')

In [85]:
oneday = np.timedelta64(1, 'D')

In [86]:
oneday

numpy.timedelta64(1,'D')

In [87]:
d + 1

numpy.datetime64('2019-06-02T23:10:01')

In [88]:
d + oneday

numpy.datetime64('2019-06-03T23:10:00')

In [89]:
oneminute = np.timedelta64(1, 'm')

In [90]:
d + oneminute

numpy.datetime64('2019-06-02T23:11:00')

In [91]:
dates = np.arange(np.datetime64('2019-06-02'), np.datetime64('2020-06-02'), 2)
dates

array(['2019-06-02', '2019-06-04', '2019-06-06', '2019-06-08',
       '2019-06-10', '2019-06-12', '2019-06-14', '2019-06-16',
       '2019-06-18', '2019-06-20', '2019-06-22', '2019-06-24',
       '2019-06-26', '2019-06-28', '2019-06-30', '2019-07-02',
       '2019-07-04', '2019-07-06', '2019-07-08', '2019-07-10',
       '2019-07-12', '2019-07-14', '2019-07-16', '2019-07-18',
       '2019-07-20', '2019-07-22', '2019-07-24', '2019-07-26',
       '2019-07-28', '2019-07-30', '2019-08-01', '2019-08-03',
       '2019-08-05', '2019-08-07', '2019-08-09', '2019-08-11',
       '2019-08-13', '2019-08-15', '2019-08-17', '2019-08-19',
       '2019-08-21', '2019-08-23', '2019-08-25', '2019-08-27',
       '2019-08-29', '2019-08-31', '2019-09-02', '2019-09-04',
       '2019-09-06', '2019-09-08', '2019-09-10', '2019-09-12',
       '2019-09-14', '2019-09-16', '2019-09-18', '2019-09-20',
       '2019-09-22', '2019-09-24', '2019-09-26', '2019-09-28',
       '2019-09-30', '2019-10-02', '2019-10-04', '2019-

# Numpy Advanced Function

In [92]:
#vectorize()

In [93]:
def foo(x):
    if x%2 == 1:
        return x**2
    else:
        return x/2

In [94]:
foo(11)

121

In [95]:
foo_v = np.vectorize(foo, otypes=[float])

In [96]:
arr

array([[6, 5, 9, 9, 5],
       [3, 9, 5, 9, 9],
       [1, 8, 9, 7, 7],
       [7, 1, 7, 1, 6],
       [4, 6, 2, 4, 6],
       [1, 4, 3, 2, 4],
       [1, 8, 5, 7, 5],
       [8, 5, 1, 3, 4],
       [8, 1, 8, 1, 3],
       [1, 8, 2, 6, 9]])

In [97]:
foo_v(arr)

array([[ 3., 25., 81., 81., 25.],
       [ 9., 81., 25., 81., 81.],
       [ 1.,  4., 81., 49., 49.],
       [49.,  1., 49.,  1.,  3.],
       [ 2.,  3.,  1.,  2.,  3.],
       [ 1.,  2.,  9.,  1.,  2.],
       [ 1.,  4., 25., 49., 25.],
       [ 4., 25.,  1.,  9.,  2.],
       [ 4.,  1.,  4.,  1.,  9.],
       [ 1.,  4.,  1.,  3., 81.]])